#!/bin/bash

if [[ $# < 3 ]]
then
        echo "not enough arguments"
            exit 1
        fi

echo "#!/bin/bash
last_mod=\$(date -u --reference=\"\$1\" +%s)
current_time=\$(date +%s)
difference=\$(((\$current_time-\$last_mod)/60/60/24))
if [[ \$difference -lt \"$2\" || \$difference -gt \"$3\" ]]
then
    exit 1;
else
    exit 0;
fi" > "script"

chmod +wx "script"

find "$1" -print0 | ./filter -z -- ./script {}
