#!/bin/bash

find_brokensymlinks()
{
    cur_file="$1"
    if [[ -e "$cur_file" && !(-L "$cur_file") ]]
    then
        if [[ -d "$cur_file" ]]
        then
            if [[ "$cur_file" == / ]]
            then
                cur_file=""
            fi
            for subfile in "$cur_file"/*
            do
                find_brokensymlinks "$subfile"
            done
        fi
    elif [[ !(-e "$cur_file") && (-L "$cur_file") ]]
    then
       echo "$cur_file"
    fi 
}

shopt -s nullglob
for file in "$@"
do
    find_brokensymlinks "$file"
done

