#!/bin/bash

for file in "$@" 
do
    if [[ -a "$file" ]] 
    then
	echo "$file"
        read new_file
        if [[ !(-a "$new_file") && -n "$new_file" ]]
	then
	    mv "$file" "$new_file"
	else	
	    while [[ (-a "$new_file" && "$new_file" != "$file") || !(-n "$new_file") ]]
	    do
		if [[ !(-a "$new_file") && -n "$new_file" ]]
		then
		    mv "$file" "$new_file"
		elif [[ -a "$new_file" && "$new_file" != "$file" ]] 
		then 
		    echo File with such name already exists.
		elif [[ !(-n "$new_file") ]]
		then 
		    echo You can\'t to have file with empty name.
		fi
		    echo "$file"
		    read new_file
	    done
	fi
    fi    
done    
