#!/bin/bash
if [[ "$#" > 1 ]]
then
    tmp_dir="/tmp/watchthis"
    if [[ !(-d $tmp_dir) ]] 
    then 
        mkdir "$tmp_dir"
    fi
    prev_dir="$tmp_dir/previous"
    cur_dir="$tmp_dir/current"
    
    echo -n "" > "$prev_dir"
    echo -n "" > "$cur_dir"

    sleeptime="$1"
    let "sleeptime += 1"
    if [[ "$sleeptime" -le 1 ]]
    then
        echo First argument should be a positive integer.
        exit 1
    else
        let "sleeptime -= 1"
    fi 
    shift

    while true 
    do
        cat "$cur_dir" > "$prev_dir"
        "$@" > "$cur_dir"
        cat "$cur_dir"
        diff -u "$prev_dir" "$cur_dir"
        sleep "$sleeptime"
    done    
fi
